using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Google.Protobuf.Reflection;
using ProtoBuf.Reflection;

namespace Lite.Serialization.Protobuf.Cli;

internal static class ProtoImporter
{
    public static int Import(List<string> protoFiles, string outputDir, ImportOptions options, bool verbose)
    {
        var set = new FileDescriptorSet();
        foreach (var proto in protoFiles)
        {
            var dir = Path.GetDirectoryName(Path.GetFullPath(proto));
            if (dir is not null) set.AddImportPath(dir);
        }
        foreach (var proto in protoFiles)
        {
            using var reader = File.OpenText(proto);
            set.Add(Path.GetFileName(proto), includeInOutput: true, source: reader);
        }
        set.Process();

        var errors = set.GetErrors();
        var hardErrors = errors.Where(e => e.IsError).ToList();
        foreach (var e in errors)
            Console.Error.WriteLine($"  {(e.IsError ? "error" : "warning")}: {e.Text}");
        if (hardErrors.Count > 0)
            throw new InvalidOperationException($"{hardErrors.Count} proto parse error(s).");

        // Flatten all message types (incl. nested) → fullName lookup, for map-entry detection & type resolution
        var allMessages = new Dictionary<string, DescriptorProto>(StringComparer.Ordinal);
        var allEnums = new HashSet<string>(StringComparer.Ordinal);
        foreach (var file in set.Files)
        {
            var pkg = string.IsNullOrEmpty(file.Package) ? "" : "." + file.Package;
            foreach (var m in file.MessageTypes) IndexMessage(m, pkg, allMessages, allEnums);
            foreach (var en in file.EnumTypes) allEnums.Add(pkg + "." + en.Name);
        }

        var written = 0;
        foreach (var file in set.Files)
        {
            if (!protoFiles.Any(p => Path.GetFileName(p) == file.Name)) continue; // skip imports

            var ns = options.Namespace
                     ?? file.Options?.CsharpNamespace
                     ?? (string.IsNullOrEmpty(file.Package) ? "Generated" : ToPascalNamespace(file.Package));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by lite-proto import from " + file.Name);
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();

            foreach (var en in file.EnumTypes)
                EmitEnum(sb, en);

            var pkg = string.IsNullOrEmpty(file.Package) ? "" : "." + file.Package;
            var flat = new List<DescriptorProto>();
            foreach (var m in file.MessageTypes) CollectMessages(m, flat);
            foreach (var m in flat)
            {
                if (m.Options?.MapEntry == true) continue; // synthetic map entry — not a user type
                EmitMessage(sb, m, options, allMessages, allEnums);
            }

            var outName = Path.GetFileNameWithoutExtension(file.Name);
            var outPath = Path.Combine(outputDir, Capitalize(outName) + ".g.cs");
            File.WriteAllText(outPath, sb.ToString());
            if (verbose) Console.WriteLine($"  → {outPath}");
            written++;
        }

        return written;
    }

    private static void IndexMessage(DescriptorProto m, string parentFqn,
        Dictionary<string, DescriptorProto> messages, HashSet<string> enums)
    {
        var fqn = parentFqn + "." + m.Name;
        messages[fqn] = m;
        foreach (var nested in m.NestedTypes) IndexMessage(nested, fqn, messages, enums);
        foreach (var en in m.EnumTypes) enums.Add(fqn + "." + en.Name);
    }

    private static void CollectMessages(DescriptorProto m, List<DescriptorProto> sink)
    {
        sink.Add(m);
        foreach (var nested in m.NestedTypes) CollectMessages(nested, sink);
    }

    private static void EmitEnum(StringBuilder sb, EnumDescriptorProto en)
    {
        sb.Append("public enum ").AppendLine(en.Name);
        sb.AppendLine("{");
        foreach (var v in en.Values)
            sb.Append("    ").Append(v.Name).Append(" = ").Append(v.Number).AppendLine(",");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitMessage(StringBuilder sb, DescriptorProto m, ImportOptions options,
        Dictionary<string, DescriptorProto> allMessages, HashSet<string> allEnums)
    {
        var fields = m.Fields.Select(f => ResolveField(f, allMessages)).ToList();
        var isStruct = DecideStruct(m.Name, fields, options);

        sb.Append("public ").Append(isStruct ? "struct " : "class ").AppendLine(m.Name);
        sb.AppendLine("{");
        if (isStruct)
            sb.Append("    public ").Append(m.Name).AppendLine("() { }");

        foreach (var f in fields)
        {
            sb.Append("    public ").Append(f.CsharpType).Append(' ').Append(f.PropertyName)
              .Append(" { get; set; }");
            if (f.DefaultInitializer is not null)
                sb.Append(" = ").Append(f.DefaultInitializer).Append(';');
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static bool DecideStruct(string name, List<ResolvedField> fields, ImportOptions options)
    {
        if (options.ForceStruct.Contains(name)) return true;
        if (options.ForceClass.Contains(name)) return false;
        if (options.AllStruct) return true;
        if (options.AllClass) return false;
        var size = fields.Sum(f => f.EstimatedSize);
        return size <= options.StructThreshold;
    }

    private sealed record ResolvedField(
        string PropertyName,
        string CsharpType,
        string? DefaultInitializer,
        int EstimatedSize);

    private static ResolvedField ResolveField(FieldDescriptorProto f, Dictionary<string, DescriptorProto> allMessages)
    {
        var propName = ToPascalCase(f.Name);
        var isRepeated = f.label == FieldDescriptorProto.Label.LabelRepeated;

        // Map detection: repeated message whose type is a synthetic map-entry
        if (isRepeated && f.type == FieldDescriptorProto.Type.TypeMessage
            && allMessages.TryGetValue(f.TypeName, out var entry) && entry.Options?.MapEntry == true)
        {
            var keyField = entry.Fields.First(x => x.Number == 1);
            var valField = entry.Fields.First(x => x.Number == 2);
            var keyType = ScalarOrRefType(keyField, allMessages);
            var valType = ScalarOrRefType(valField, allMessages);
            return new ResolvedField(propName,
                $"global::System.Collections.Generic.Dictionary<{keyType}, {valType}>",
                "new()", 8);
        }

        if (isRepeated)
        {
            var elemType = ScalarOrRefType(f, allMessages);
            return new ResolvedField(propName,
                $"global::System.Collections.Generic.List<{elemType}>", "new()", 8);
        }

        var (cs, init, size) = ScalarFieldInfo(f, allMessages);
        return new ResolvedField(propName, cs, init, size);
    }

    private static string ScalarOrRefType(FieldDescriptorProto f, Dictionary<string, DescriptorProto> allMessages)
        => ScalarFieldInfo(f, allMessages).CsharpType;

    private static (string CsharpType, string? Init, int Size) ScalarFieldInfo(
        FieldDescriptorProto f, Dictionary<string, DescriptorProto> allMessages)
    {
        switch (f.type)
        {
            case FieldDescriptorProto.Type.TypeDouble: return ("double", null, 8);
            case FieldDescriptorProto.Type.TypeFloat: return ("float", null, 4);
            case FieldDescriptorProto.Type.TypeInt64:
            case FieldDescriptorProto.Type.TypeSint64:
            case FieldDescriptorProto.Type.TypeSfixed64: return ("long", null, 8);
            case FieldDescriptorProto.Type.TypeUint64:
            case FieldDescriptorProto.Type.TypeFixed64: return ("ulong", null, 8);
            case FieldDescriptorProto.Type.TypeInt32:
            case FieldDescriptorProto.Type.TypeSint32:
            case FieldDescriptorProto.Type.TypeSfixed32: return ("int", null, 4);
            case FieldDescriptorProto.Type.TypeUint32:
            case FieldDescriptorProto.Type.TypeFixed32: return ("uint", null, 4);
            case FieldDescriptorProto.Type.TypeBool: return ("bool", null, 1);
            case FieldDescriptorProto.Type.TypeString: return ("string", "\"\"", 8);
            case FieldDescriptorProto.Type.TypeBytes: return ("byte[]", "global::System.Array.Empty<byte>()", 8);
            case FieldDescriptorProto.Type.TypeEnum: return (LastSegment(f.TypeName), null, 4);
            case FieldDescriptorProto.Type.TypeMessage: return (LastSegment(f.TypeName), null, 8);
            default: return ("object", null, 8);
        }
    }

    private static string LastSegment(string fqn)
    {
        var idx = fqn.LastIndexOf('.');
        return idx >= 0 ? fqn.Substring(idx + 1) : fqn;
    }

    private static string ToPascalCase(string snake)
    {
        var sb = new StringBuilder(snake.Length);
        var upperNext = true;
        foreach (var c in snake)
        {
            if (c == '_') { upperNext = true; continue; }
            sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
            upperNext = false;
        }
        return sb.Length == 0 ? snake : sb.ToString();
    }

    private static string ToPascalNamespace(string package) =>
        string.Join('.', package.Split('.').Select(Capitalize));

    private static string Capitalize(string s) =>
        string.IsNullOrEmpty(s) ? s : char.ToUpperInvariant(s[0]) + s.Substring(1);
}
